
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 7;
  public static final int PLUS = 5;
  public static final int RBRACE = 12;
  public static final int RPAREN = 10;
  public static final int INT = 13;
  public static final int SEMI = 2;
  public static final int RETURN = 17;
  public static final int TRUE = 18;
  public static final int LPAREN = 9;
  public static final int LBRACE = 11;
  public static final int ID = 21;
  public static final int COMMA = 3;
  public static final int NUMBER = 20;
  public static final int EOF = 0;
  public static final int DIVIDE = 8;
  public static final int MAIN = 16;
  public static final int FALSE = 19;
  public static final int MINUS = 6;
  public static final int error = 1;
  public static final int ASSIGN = 4;
  public static final int BOOL = 14;
  public static final int VOID = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "COMMA",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "INT",
  "BOOL",
  "VOID",
  "MAIN",
  "RETURN",
  "TRUE",
  "FALSE",
  "NUMBER",
  "ID"
  };
}

